<a href="https://colab.research.google.com/github/UjjwalVats47/Data_Science/blob/main/Text_processing_NLP_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
import pandas as pd

In [36]:
with open("text preprocessing data 1.txt", 'r') as f:
    lines = f.readlines()
df = pd.DataFrame(lines, columns=['text_content'])
display(df.head())

                                        text_content
0  In recent years, deep learning, first proposed...
1  advances [2]. Because of the unsupervised-laye...
2  obstacle to the training of deep neural networ...
3  (AI) researchers have turned to deep learning,...
4  thousands, and even millions of layers [4]. Th...

In [37]:
df.shape

(50, 1)

In [38]:
df['text_content'] = df['text_content'].str.lower()

In [39]:
df

                                         text_content
0   in recent years, deep learning, first proposed...
1   advances [2]. because of the unsupervised-laye...
2   obstacle to the training of deep neural networ...
3   (ai) researchers have turned to deep learning,...
4   thousands, and even millions of layers [4]. th...
5   neural networks, such as convolutional neural ...
6   long short-term memory networks (lstms) [7], b...
7   the advances and popularity of deep learning, ...
8   computing devices specially designed for deep ...
9   machine learning techniques and make deep lear...
10                                the 21st century.\n
11  given significant advances in deep learning, v...
12  fulfill software engineering tasks [10]. altho...
13  has been successfully applied to a wide range ...
14  manufacturing [12], biomedical engineering [13...
15  tasks, such as code generation [15], code comp...
16  substantially improving the state-of-the-art. ...
17  software engineering is the significant advanc...
18  that various and massive software engineering ...
19  models. with the popularity of open-source sof...
20  requirements, source code, documents, bug repo...
21  trace relationships among different artifacts....
22  for software engineering tasks feasible. to ou...
23  learning for software engineering (e.g., yang ...
24  these surveys provide some overall pictures of...
25  there is still a lack of detailed analyses of ...
26  techniques from the perspective of each subare...
27  in this paper, we present a detailed survey co...
28  major software engineering subareas. we choose...
29  of deep learning for the whole discipline of s...
30  individual subareas for the following reasons....
31  researchers follow a divide-and-conquer strate...
32  however, the advances of deep learning may pro...
33  in different subareas to push forward the soft...
34  may provide a common means to revolutionize so...
35  that a survey of deep learning in all software...
36  engineering researchers. second, deep learning...
37  techniques for software engineering are thus h...
38  as different subareas of software engineering ...
39  subareas into one survey would help researcher...
40  weaknesses of different deep learning techniqu...
41  code may impact all subareas related to the co...
42  one issue that raises in preparing this survey...
43  applications of deep learning techniques may t...
44  facing such a subarea, where there are very fe...
45  hardly reflect the essence of deep learning re...
46  subareas of software engineering, we focus on ...
47  impacts. fortunately, deep learning has deeply...
48  we selected for surveying in this paper, we ca...
49                  learning for software engineering

Removing HTML Tags

In [40]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [41]:
df['text_content'] = df['text_content'].apply(remove_html_tags)

In [42]:
df['text_content'][15]

'tasks, such as code generation [15], code completion [16], code summarization [17], software refactoring [18], code search [19], fault localization [20], automated program repair [21], vulnerability detection [22], and software testing [23]. in all such tasks, deep learning techniques have been proven useful,\n'

Removing link text

In [43]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [44]:
df['text_content']= df['text_content'].apply(remove_url)

In [45]:
df['text_content']

0     in recent years, deep learning, first proposed...
1     advances [2]. because of the unsupervised-laye...
2     obstacle to the training of deep neural networ...
3     (ai) researchers have turned to deep learning,...
4     thousands, and even millions of layers [4]. th...
5     neural networks, such as convolutional neural ...
6     long short-term memory networks (lstms) [7], b...
7     the advances and popularity of deep learning, ...
8     computing devices specially designed for deep ...
9     machine learning techniques and make deep lear...
10                                  the 21st century.\n
11    given significant advances in deep learning, v...
12    fulfill software engineering tasks [10]. altho...
13    has been successfully applied to a wide range ...
14    manufacturing [12], biomedical engineering [13...
15    tasks, such as code generation [15], code comp...
16    substantially improving the state-of-the-art. ...
17    software engineering is the significant advanc...
18    that various and massive software engineering ...
19    models. with the popularity of open-source sof...
20    requirements, source code, documents, bug repo...
21    trace relationships among different artifacts....
22    for software engineering tasks feasible. to ou...
23    learning for software engineering (e.g., yang ...
24    these surveys provide some overall pictures of...
25    there is still a lack of detailed analyses of ...
26    techniques from the perspective of each subare...
27    in this paper, we present a detailed survey co...
28    major software engineering subareas. we choose...
29    of deep learning for the whole discipline of s...
30    individual subareas for the following reasons....
31    researchers follow a divide-and-conquer strate...
32    however, the advances of deep learning may pro...
33    in different subareas to push forward the soft...
34    may provide a common means to revolutionize so...
35    that a survey of deep learning in all software...
36    engineering researchers. second, deep learning...
37    techniques for software engineering are thus h...
38    as different subareas of software engineering ...
39    subareas into one survey would help researcher...
40    weaknesses of different deep learning techniqu...
41    code may impact all subareas related to the co...
42    one issue that raises in preparing this survey...
43    applications of deep learning techniques may t...
44    facing such a subarea, where there are very fe...
45    hardly reflect the essence of deep learning re...
46    subareas of software engineering, we focus on ...
47    impacts. fortunately, deep learning has deeply...
48    we selected for surveying in this paper, we ca...
49                    learning for software engineering
Name: text_content, dtype: object

Removing Bracketed Numbers/Citations

In [46]:
df['text_content'] = df['text_content'].str.replace(r'\[\d+\]', '', regex=True)

Removing \n

In [47]:
df['text_content'] = df['text_content'].str.replace('\n',' ')

Removing punctuation

In [48]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [49]:


exclude = string.punctuation

In [50]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,' ')
    return text

In [51]:
df['text_content'] = df['text_content'].apply(remove_punc)

In [52]:
df['text_content'][1]

'advances   because of the unsupervised layer wise training proposed by hinton et al    the major '

Removing Stop words

In [53]:
import nltk

In [54]:
from nltk.corpus import stopwords

In [55]:
nltk.download ("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [56]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [57]:
st=stopwords.words('english')

In [58]:
st

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [59]:
df2= ''

In [60]:
for text_entry in df['text_content']:
    # Ensuring text_entry is a string before splitting
    if isinstance(text_entry, str):
        words = text_entry.split()
        for word in words:
            if word not in st:
                df2 += word + ' '

In [61]:
df2

'recent years deep learning first proposed hinton et al 2006 achieved highly impressive advances unsupervised layer wise training proposed hinton et al major obstacle training deep neural networks removed since artificial intelligence ai researchers turned deep learning constructing deep neural networks containing dozens thousands even millions layers also proposed various novel structures deep neural networks convolutional neural networks cnns recurrent neural networks rnns long short term memory networks lstms bidirectional lstm transformer advances popularity deep learning hardware vendors like nvidia release powerful computing devices specially designed deep learning together significantly push forward machine learning techniques make deep learning based ai one promising techniques 21st century given significant advances deep learning various deep learning techniques employed fulfill software engineering tasks although natural language processing nlp image video processing speech processing major targets current deep learning techniques deep learning successfully applied wide range various domains including data mining machine manufacturing biomedical engineering information security concerning software engineering researchers successfully exploited various deep learning techniques various important tasks code generation code completion code summarization software refactoring code search fault localization automated program repair vulnerability detection software testing tasks deep learning techniques proven useful substantially improving state art one possible reason success deep learning based software engineering significant advances deep learning techniques another possible reason various massive software engineering data publicly available training advanced neural models popularity open source software applications developers share massive software requirements source code documents bug reports patches test cases online discussions logs trace relationships among different artifacts data make training specialized deep neural models software engineering tasks feasible knowledge already several surveys deep learning software engineering e g yang et al watson et al niu et al although surveys provide overall pictures applications deep learning software engineering still lack detailed analyses progress challenges opportunities deep learning techniques perspective subarea software engineering influenced deep learning paper present detailed survey covering applications deep learning techniques major software engineering subareas choose provide one survey cover technical research deep learning whole discipline software engineering instead several surveys different individual subareas following reasons first software engineering one central objective researchers follow divide conquer strategy divide software engineering different subareas however advances deep learning may provide us opportunity break boundaries research different subareas push forward software engineering discipline whole deep learning may provide common means revolutionize software engineering future therefore believe survey deep learning software engineering subareas may beneficial software engineering researchers second deep learning belongs representation learning deep learning techniques software engineering thus highly specific different artifacts software development different subareas software engineering typically share common artifacts putting different subareas one survey would help researchers different subareas understand strengths weaknesses different deep learning techniques example deep learning technique based source code may impact subareas related comprehension generation modification codes one issue raises preparing survey software engineering big discipline applications deep learning techniques may thus touch subareas uninfluential way facing subarea deep learning papers feel papers hardly reflect essence deep learning research subarea therefore instead covering subareas software engineering focus subareas deep learning already significant impacts fortunately deep learning deeply impacted software engineering subareas selected surveying paper already form general insightful picture deep learning software engineering '

In [62]:
tokens=re.findall("[\w']+",df2)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_1867/2361521108.py:1: SyntaxWarning: invalid escape sequence '\w'
  tokens=re.findall("[\w']+",df2)

In [63]:
tokens

['recent',
 'years',
 'deep',
 'learning',
 'first',
 'proposed',
 'hinton',
 'et',
 'al',
 '2006',
 'achieved',
 'highly',
 'impressive',
 'advances',
 'unsupervised',
 'layer',
 'wise',
 'training',
 'proposed',
 'hinton',
 'et',
 'al',
 'major',
 'obstacle',
 'training',
 'deep',
 'neural',
 'networks',
 'removed',
 'since',
 'artificial',
 'intelligence',
 'ai',
 'researchers',
 'turned',
 'deep',
 'learning',
 'constructing',
 'deep',
 'neural',
 'networks',
 'containing',
 'dozens',
 'thousands',
 'even',
 'millions',
 'layers',
 'also',
 'proposed',
 'various',
 'novel',
 'structures',
 'deep',
 'neural',
 'networks',
 'convolutional',
 'neural',
 'networks',
 'cnns',
 'recurrent',
 'neural',
 'networks',
 'rnns',
 'long',
 'short',
 'term',
 'memory',
 'networks',
 'lstms',
 'bidirectional',
 'lstm',
 'transformer',
 'advances',
 'popularity',
 'deep',
 'learning',
 'hardware',
 'vendors',
 'like',
 'nvidia',
 'release',
 'powerful',
 'computing',
 'devices',
 'specially',
 'designed',
 'deep',
 'learning',
 'together',
 'significantly',
 'push',
 'forward',
 'machine',
 'learning',
 'techniques',
 'make',
 'deep',
 'learning',
 'based',
 'ai',
 'one',
 'promising',
 'techniques',
 '21st',
 'century',
 'given',
 'significant',
 'advances',
 'deep',
 'learning',
 'various',
 'deep',
 'learning',
 'techniques',
 'employed',
 'fulfill',
 'software',
 'engineering',
 'tasks',
 'although',
 'natural',
 'language',
 'processing',
 'nlp',
 'image',
 'video',
 'processing',
 'speech',
 'processing',
 'major',
 'targets',
 'current',
 'deep',
 'learning',
 'techniques',
 'deep',
 'learning',
 'successfully',
 'applied',
 'wide',
 'range',
 'various',
 'domains',
 'including',
 'data',
 'mining',
 'machine',
 'manufacturing',
 'biomedical',
 'engineering',
 'information',
 'security',
 'concerning',
 'software',
 'engineering',
 'researchers',
 'successfully',
 'exploited',
 'various',
 'deep',
 'learning',
 'techniques',
 'various',
 'important',
 'tasks',
 'code',
 'generation',
 'code',
 'completion',
 'code',
 'summarization',
 'software',
 'refactoring',
 'code',
 'search',
 'fault',
 'localization',
 'automated',
 'program',
 'repair',
 'vulnerability',
 'detection',
 'software',
 'testing',
 'tasks',
 'deep',
 'learning',
 'techniques',
 'proven',
 'useful',
 'substantially',
 'improving',
 'state',
 'art',
 'one',
 'possible',
 'reason',
 'success',
 'deep',
 'learning',
 'based',
 'software',
 'engineering',
 'significant',
 'advances',
 'deep',
 'learning',
 'techniques',
 'another',
 'possible',
 'reason',
 'various',
 'massive',
 'software',
 'engineering',
 'data',
 'publicly',
 'available',
 'training',
 'advanced',
 'neural',
 'models',
 'popularity',
 'open',
 'source',
 'software',
 'applications',
 'developers',
 'share',
 'massive',
 'software',
 'requirements',
 'source',
 'code',
 'documents',
 'bug',
 'reports',
 'patches',
 'test',
 'cases',
 'online',
 'discussions',
 'logs',
 'trace',
 'relationships',
 'among',
 'different',
 'artifacts',
 'data',
 'make',
 'training',
 'specialized',
 'deep',
 'neural',
 'models',
 'software',
 'engineering',
 'tasks',
 'feasible',
 'knowledge',
 'already',
 'several',
 'surveys',
 'deep',
 'learning',
 'software',
 'engineering',
 'e',
 'g',
 'yang',
 'et',
 'al',
 'watson',
 'et',
 'al',
 'niu',
 'et',
 'al',
 'although',
 'surveys',
 'provide',
 'overall',
 'pictures',
 'applications',
 'deep',
 'learning',
 'software',
 'engineering',
 'still',
 'lack',
 'detailed',
 'analyses',
 'progress',
 'challenges',
 'opportunities',
 'deep',
 'learning',
 'techniques',
 'perspective',
 'subarea',
 'software',
 'engineering',
 'influenced',
 'deep',
 'learning',
 'paper',
 'present',
 'detailed',
 'survey',
 'covering',
 'applications',
 'deep',
 'learning',
 'techniques',
 'major',
 'software',
 'engineering',
 'subareas',
 'choose',
 'provide',
 'one',
 'survey',
 'cover',
 'technical',
 'research',
 'deep',
 'learning',
 'whole',
 'discipline',
 'software',
 'engineering',
 'instead',
 'several',
 'surveys',
 'different',
 'individual',
 'subareas',
 'following',
 'reasons',
 'first',
 'software',
 'engineering',
 'one',
 'central',
 'objective',
 'researchers',
 'follow',
 'divide',
 'conquer',
 'strategy',
 'divide',
 'software',
 'engineering',
 'different',
 'subareas',
 'however',
 'advances',
 'deep',
 'learning',
 'may',
 'provide',
 'us',
 'opportunity',
 'break',
 'boundaries',
 'research',
 'different',
 'subareas',
 'push',
 'forward',
 'software',
 'engineering',
 'discipline',
 'whole',
 'deep',
 'learning',
 'may',
 'provide',
 'common',
 'means',
 'revolutionize',
 'software',
 'engineering',
 'future',
 'therefore',
 'believe',
 'survey',
 'deep',
 'learning',
 'software',
 'engineering',
 'subareas',
 'may',
 'beneficial',
 'software',
 'engineering',
 'researchers',
 'second',
 'deep',
 'learning',
 'belongs',
 'representation',
 'learning',
 'deep',
 'learning',
 'techniques',
 'software',
 'engineering',
 'thus',
 'highly',
 'specific',
 'different',
 'artifacts',
 'software',
 'development',
 'different',
 'subareas',
 'software',
 'engineering',
 'typically',
 'share',
 'common',
 'artifacts',
 'putting',
 'different',
 'subareas',
 'one',
 'survey',
 'would',
 'help',
 'researchers',
 'different',
 'subareas',
 'understand',
 'strengths',
 'weaknesses',
 'different',
 'deep',
 'learning',
 'techniques',
 'example',
 'deep',
 'learning',
 'technique',
 'based',
 'source',
 'code',
 'may',
 'impact',
 'subareas',
 'related',
 'comprehension',
 'generation',
 'modification',
 'codes',
 'one',
 'issue',
 'raises',
 'preparing',
 'survey',
 'software',
 'engineering',
 'big',
 'discipline',
 'applications',
 'deep',
 'learning',
 'techniques',
 'may',
 'thus',
 'touch',
 'subareas',
 'uninfluential',
 'way',
 'facing',
 'subarea',
 'deep',
 'learning',
 'papers',
 'feel',
 'papers',
 'hardly',
 'reflect',
 'essence',
 'deep',
 'learning',
 'research',
 'subarea',
 'therefore',
 'instead',
 'covering',
 'subareas',
 'software',
 'engineering',
 'focus',
 'subareas',
 'deep',
 'learning',
 'already',
 'significant',
 'impacts',
 'fortunately',
 'deep',
 'learning',
 'deeply',
 'impacted',
 'software',
 'engineering',
 'subareas',
 'selected',
 'surveying',
 'paper',
 'already',
 'form',
 'general',
 'insightful',
 'picture',
 'deep',
 'learning',
 'software',
 'engineering']

In [64]:
from nltk.tokenize import word_tokenize, sent_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [65]:
word_tokenize(df2)

['recent',
 'years',
 'deep',
 'learning',
 'first',
 'proposed',
 'hinton',
 'et',
 'al',
 '2006',
 'achieved',
 'highly',
 'impressive',
 'advances',
 'unsupervised',
 'layer',
 'wise',
 'training',
 'proposed',
 'hinton',
 'et',
 'al',
 'major',
 'obstacle',
 'training',
 'deep',
 'neural',
 'networks',
 'removed',
 'since',
 'artificial',
 'intelligence',
 'ai',
 'researchers',
 'turned',
 'deep',
 'learning',
 'constructing',
 'deep',
 'neural',
 'networks',
 'containing',
 'dozens',
 'thousands',
 'even',
 'millions',
 'layers',
 'also',
 'proposed',
 'various',
 'novel',
 'structures',
 'deep',
 'neural',
 'networks',
 'convolutional',
 'neural',
 'networks',
 'cnns',
 'recurrent',
 'neural',
 'networks',
 'rnns',
 'long',
 'short',
 'term',
 'memory',
 'networks',
 'lstms',
 'bidirectional',
 'lstm',
 'transformer',
 'advances',
 'popularity',
 'deep',
 'learning',
 'hardware',
 'vendors',
 'like',
 'nvidia',
 'release',
 'powerful',
 'computing',
 'devices',
 'specially',
 'designed',
 'deep',
 'learning',
 'together',
 'significantly',
 'push',
 'forward',
 'machine',
 'learning',
 'techniques',
 'make',
 'deep',
 'learning',
 'based',
 'ai',
 'one',
 'promising',
 'techniques',
 '21st',
 'century',
 'given',
 'significant',
 'advances',
 'deep',
 'learning',
 'various',
 'deep',
 'learning',
 'techniques',
 'employed',
 'fulfill',
 'software',
 'engineering',
 'tasks',
 'although',
 'natural',
 'language',
 'processing',
 'nlp',
 'image',
 'video',
 'processing',
 'speech',
 'processing',
 'major',
 'targets',
 'current',
 'deep',
 'learning',
 'techniques',
 'deep',
 'learning',
 'successfully',
 'applied',
 'wide',
 'range',
 'various',
 'domains',
 'including',
 'data',
 'mining',
 'machine',
 'manufacturing',
 'biomedical',
 'engineering',
 'information',
 'security',
 'concerning',
 'software',
 'engineering',
 'researchers',
 'successfully',
 'exploited',
 'various',
 'deep',
 'learning',
 'techniques',
 'various',
 'important',
 'tasks',
 'code',
 'generation',
 'code',
 'completion',
 'code',
 'summarization',
 'software',
 'refactoring',
 'code',
 'search',
 'fault',
 'localization',
 'automated',
 'program',
 'repair',
 'vulnerability',
 'detection',
 'software',
 'testing',
 'tasks',
 'deep',
 'learning',
 'techniques',
 'proven',
 'useful',
 'substantially',
 'improving',
 'state',
 'art',
 'one',
 'possible',
 'reason',
 'success',
 'deep',
 'learning',
 'based',
 'software',
 'engineering',
 'significant',
 'advances',
 'deep',
 'learning',
 'techniques',
 'another',
 'possible',
 'reason',
 'various',
 'massive',
 'software',
 'engineering',
 'data',
 'publicly',
 'available',
 'training',
 'advanced',
 'neural',
 'models',
 'popularity',
 'open',
 'source',
 'software',
 'applications',
 'developers',
 'share',
 'massive',
 'software',
 'requirements',
 'source',
 'code',
 'documents',
 'bug',
 'reports',
 'patches',
 'test',
 'cases',
 'online',
 'discussions',
 'logs',
 'trace',
 'relationships',
 'among',
 'different',
 'artifacts',
 'data',
 'make',
 'training',
 'specialized',
 'deep',
 'neural',
 'models',
 'software',
 'engineering',
 'tasks',
 'feasible',
 'knowledge',
 'already',
 'several',
 'surveys',
 'deep',
 'learning',
 'software',
 'engineering',
 'e',
 'g',
 'yang',
 'et',
 'al',
 'watson',
 'et',
 'al',
 'niu',
 'et',
 'al',
 'although',
 'surveys',
 'provide',
 'overall',
 'pictures',
 'applications',
 'deep',
 'learning',
 'software',
 'engineering',
 'still',
 'lack',
 'detailed',
 'analyses',
 'progress',
 'challenges',
 'opportunities',
 'deep',
 'learning',
 'techniques',
 'perspective',
 'subarea',
 'software',
 'engineering',
 'influenced',
 'deep',
 'learning',
 'paper',
 'present',
 'detailed',
 'survey',
 'covering',
 'applications',
 'deep',
 'learning',
 'techniques',
 'major',
 'software',
 'engineering',
 'subareas',
 'choose',
 'provide',
 'one',
 'survey',
 'cover',
 'technical',
 'research',
 'deep',
 'learning',
 'whole',
 'discipline',
 'software',
 'engineering',
 'instead',
 'several',
 'surveys',
 'different',
 'individual',
 'subareas',
 'following',
 'reasons',
 'first',
 'software',
 'engineering',
 'one',
 'central',
 'objective',
 'researchers',
 'follow',
 'divide',
 'conquer',
 'strategy',
 'divide',
 'software',
 'engineering',
 'different',
 'subareas',
 'however',
 'advances',
 'deep',
 'learning',
 'may',
 'provide',
 'us',
 'opportunity',
 'break',
 'boundaries',
 'research',
 'different',
 'subareas',
 'push',
 'forward',
 'software',
 'engineering',
 'discipline',
 'whole',
 'deep',
 'learning',
 'may',
 'provide',
 'common',
 'means',
 'revolutionize',
 'software',
 'engineering',
 'future',
 'therefore',
 'believe',
 'survey',
 'deep',
 'learning',
 'software',
 'engineering',
 'subareas',
 'may',
 'beneficial',
 'software',
 'engineering',
 'researchers',
 'second',
 'deep',
 'learning',
 'belongs',
 'representation',
 'learning',
 'deep',
 'learning',
 'techniques',
 'software',
 'engineering',
 'thus',
 'highly',
 'specific',
 'different',
 'artifacts',
 'software',
 'development',
 'different',
 'subareas',
 'software',
 'engineering',
 'typically',
 'share',
 'common',
 'artifacts',
 'putting',
 'different',
 'subareas',
 'one',
 'survey',
 'would',
 'help',
 'researchers',
 'different',
 'subareas',
 'understand',
 'strengths',
 'weaknesses',
 'different',
 'deep',
 'learning',
 'techniques',
 'example',
 'deep',
 'learning',
 'technique',
 'based',
 'source',
 'code',
 'may',
 'impact',
 'subareas',
 'related',
 'comprehension',
 'generation',
 'modification',
 'codes',
 'one',
 'issue',
 'raises',
 'preparing',
 'survey',
 'software',
 'engineering',
 'big',
 'discipline',
 'applications',
 'deep',
 'learning',
 'techniques',
 'may',
 'thus',
 'touch',
 'subareas',
 'uninfluential',
 'way',
 'facing',
 'subarea',
 'deep',
 'learning',
 'papers',
 'feel',
 'papers',
 'hardly',
 'reflect',
 'essence',
 'deep',
 'learning',
 'research',
 'subarea',
 'therefore',
 'instead',
 'covering',
 'subareas',
 'software',
 'engineering',
 'focus',
 'subareas',
 'deep',
 'learning',
 'already',
 'significant',
 'impacts',
 'fortunately',
 'deep',
 'learning',
 'deeply',
 'impacted',
 'software',
 'engineering',
 'subareas',
 'selected',
 'surveying',
 'paper',
 'already',
 'form',
 'general',
 'insightful',
 'picture',
 'deep',
 'learning',
 'software',
 'engineering']

In [66]:
sent_tokenize(df2)

['recent years deep learning first proposed hinton et al 2006 achieved highly impressive advances unsupervised layer wise training proposed hinton et al major obstacle training deep neural networks removed since artificial intelligence ai researchers turned deep learning constructing deep neural networks containing dozens thousands even millions layers also proposed various novel structures deep neural networks convolutional neural networks cnns recurrent neural networks rnns long short term memory networks lstms bidirectional lstm transformer advances popularity deep learning hardware vendors like nvidia release powerful computing devices specially designed deep learning together significantly push forward machine learning techniques make deep learning based ai one promising techniques 21st century given significant advances deep learning various deep learning techniques employed fulfill software engineering tasks although natural language processing nlp image video processing speech processing major targets current deep learning techniques deep learning successfully applied wide range various domains including data mining machine manufacturing biomedical engineering information security concerning software engineering researchers successfully exploited various deep learning techniques various important tasks code generation code completion code summarization software refactoring code search fault localization automated program repair vulnerability detection software testing tasks deep learning techniques proven useful substantially improving state art one possible reason success deep learning based software engineering significant advances deep learning techniques another possible reason various massive software engineering data publicly available training advanced neural models popularity open source software applications developers share massive software requirements source code documents bug reports patches test cases online discussions logs trace relationships among different artifacts data make training specialized deep neural models software engineering tasks feasible knowledge already several surveys deep learning software engineering e g yang et al watson et al niu et al although surveys provide overall pictures applications deep learning software engineering still lack detailed analyses progress challenges opportunities deep learning techniques perspective subarea software engineering influenced deep learning paper present detailed survey covering applications deep learning techniques major software engineering subareas choose provide one survey cover technical research deep learning whole discipline software engineering instead several surveys different individual subareas following reasons first software engineering one central objective researchers follow divide conquer strategy divide software engineering different subareas however advances deep learning may provide us opportunity break boundaries research different subareas push forward software engineering discipline whole deep learning may provide common means revolutionize software engineering future therefore believe survey deep learning software engineering subareas may beneficial software engineering researchers second deep learning belongs representation learning deep learning techniques software engineering thus highly specific different artifacts software development different subareas software engineering typically share common artifacts putting different subareas one survey would help researchers different subareas understand strengths weaknesses different deep learning techniques example deep learning technique based source code may impact subareas related comprehension generation modification codes one issue raises preparing survey software engineering big discipline applications deep learning techniques may thus touch subareas uninfluential way facing subarea deep learning papers feel papers hardly reflect essence deep learning research subarea therefore instead covering subareas software engineering focus subareas deep learning already significant impacts fortunately deep learning deeply impacted software engineering subareas selected surveying paper already form general insightful picture deep learning software engineering']

Removing Inflection(Stemming Method)

In [67]:
# from nltk.stem.porter import PorterStemmer
# ps=PorterStemmer()

# def port_stem(text):
#     return" ".join([ps.stem(word) for word in text.split()])

In [68]:
# port_stem(text=df2)

Removing Inflection(Lemmatization Method)

In [69]:
from nltk.stem import WordNetLemmatizer
wnl= WordNetLemmatizer()

In [72]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [74]:
def lemmatize_text(text):
    words = text.split()
    lemmatized_words = [wnl.lemmatize(word) for word in words]
    return ' '.join(lemmatized_words)

lemmatized_df2 = lemmatize_text(df2)
print(lemmatized_df2)

recent year deep learning first proposed hinton et al 2006 achieved highly impressive advance unsupervised layer wise training proposed hinton et al major obstacle training deep neural network removed since artificial intelligence ai researcher turned deep learning constructing deep neural network containing dozen thousand even million layer also proposed various novel structure deep neural network convolutional neural network cnns recurrent neural network rnns long short term memory network lstms bidirectional lstm transformer advance popularity deep learning hardware vendor like nvidia release powerful computing device specially designed deep learning together significantly push forward machine learning technique make deep learning based ai one promising technique 21st century given significant advance deep learning various deep learning technique employed fulfill software engineering task although natural language processing nlp image video processing speech processing major target current deep learning technique deep learning successfully applied wide range various domain including data mining machine manufacturing biomedical engineering information security concerning software engineering researcher successfully exploited various deep learning technique various important task code generation code completion code summarization software refactoring code search fault localization automated program repair vulnerability detection software testing task deep learning technique proven useful substantially improving state art one possible reason success deep learning based software engineering significant advance deep learning technique another possible reason various massive software engineering data publicly available training advanced neural model popularity open source software application developer share massive software requirement source code document bug report patch test case online discussion log trace relationship among different artifact data make training specialized deep neural model software engineering task feasible knowledge already several survey deep learning software engineering e g yang et al watson et al niu et al although survey provide overall picture application deep learning software engineering still lack detailed analysis progress challenge opportunity deep learning technique perspective subarea software engineering influenced deep learning paper present detailed survey covering application deep learning technique major software engineering subareas choose provide one survey cover technical research deep learning whole discipline software engineering instead several survey different individual subareas following reason first software engineering one central objective researcher follow divide conquer strategy divide software engineering different subareas however advance deep learning may provide u opportunity break boundary research different subareas push forward software engineering discipline whole deep learning may provide common mean revolutionize software engineering future therefore believe survey deep learning software engineering subareas may beneficial software engineering researcher second deep learning belongs representation learning deep learning technique software engineering thus highly specific different artifact software development different subareas software engineering typically share common artifact putting different subareas one survey would help researcher different subareas understand strength weakness different deep learning technique example deep learning technique based source code may impact subareas related comprehension generation modification code one issue raise preparing survey software engineering big discipline application deep learning technique may thus touch subareas uninfluential way facing subarea deep learning paper feel paper hardly reflect essence deep learning research subarea therefore instead covering subareas software engineering focus subareas deep learning already significant impact fortunately deep learning deeply impacted software engineering subareas selected surveying paper already form general insightful picture deep learning software engineering